# Generated by Django 5.1.5 on 2025-02-13 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0004_alter_borrowing_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="borrowing",
            name="created_at",
        ),
    ]
